common:
    system : "pp"
    energy : "5.36 TeV" #center-of-mass energy in TeV
    meson : "pi0"
    period : "LHC24aq_LHC24ap"
    plotting_type : "thesis"
    background_fit : "Asymmetric Gaussian fit"
    # pt_bin: [0., 0.2, 0.40,  0.50, 0.60, 0.70, 0.80, 0.90, 1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 2.50, 3.00,  3.50, 4.00, 4.50, 5.00, 5.5, 6.00,  7.00, 8.00, 9.00, 15.0, 20.0]
    #pt_bin: [0., 0.50, 1.00, 1.25, 1.5, 2.0, 2.50, 3.00, 4.00, 5.00, 7.00, 20.0]
    pt_bin: [0., 0.2, 0.4, 0.6, 0.8, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.5, 5.0, 6.0, 7.0, 8.0, 10.0, 12., 14., 16., 18., 20.0]
    #pt_bin: [0.40, 0.60, 0.80, 1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.50, 5.00, 5.50, 6.00, 7.00, 8.00, 9.00, 10.0, 12.0, 15.0, 20.0]
    start_pT_bin: 1
    RV0_bin: [4,30,58,90]
    occupancy_bin: ["0", "more"] #0, 10k, 30k, more
data:
    subsystems:
        diff_cent:
        - name: "pi0eta-to-gammagamma-pcmpcm"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
          fit_parameters_name: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.3,0.45]
          fit_param_limit_max: [1.2,1.02,1.3,1.1]
          fit_func: ["gausexplinear"]
          fit_range: [[0.04, 0.2]]
          scale_mix_range: [[0.18, 0.25]]
          yield_range: [[0.035, 0.02]]

