common:
    system : "pO"
    energy : "9.61 TeV" #center-of-mass energy in TeV
    meson : "eta"
    period : "LHC25h2c"
    plotting_type: "thesis"
    background_fit: "Asymmetric Gaussian fit"
    do_ptspectrum: True
    #pt_bin: [1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 2.50, 3.00,  3.50, 4.00, 4.50, 5.00, 5.5, 6.00,  7.00, 8.00, 9.00, 15.0]
    # pt_bin: [0., 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 5.0, 10.0, 20.0]
    #pt_bin: [0.5, 1., 2.0, 3.0, 5.0, 7.0, 9.0, 10.0, 20.0]
    #pt_bin: [1., 2.0, 3.0, 4.0, 6.0, 8.0, 10.0, 12.0]
    pt_bin: [0.5, 1.0, 1.50, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0] #was 5.0, 10.0
    #pt_bin: [1., 2.0, 3.0, 4.0, 6.0, 8.0, 10.0, 12.0]
    #pt_bin: [1., 2.0, 3.0, 5.0, 7.0, 9.0, 10.0, 20.0] #was 5.0, 10.0
    RV0_bin: [4,30,58,90]
    start_pT_bin: 1
    #fit_sig: ["cb"]
    #fit_bkg: ["pol1"]
    fit_min: [0.4]
    fit_max: [0.7]
    integral_min: [0.65] #0.62
    integral_max: [0.7] #0.66
    yield_min: [0.065]
    yield_max: [0.04]
data:
    fit_func: ["gausexplinear"]
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems:
        # - name: "PCMPCM"
          # cuts:
        - name: "pi0eta-to-gammagamma-pcmpcm"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
             # initial values: []
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.97,0.926,0.85,0.8]
          fit_limit_max: [1.2,1.02,1.5,1.1]
mc:
    fit_func: ["gausexp"]
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems:
        # - name: "PCMPCM"
          # cuts:
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_4_30"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_RV0_4_30"
              # initial values: []
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.999,0.926,0.6,0.6]
          fit_limit_max: [1.1,1.02,1.5,1.2]
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_30_58"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_RV0_30_58"
              # initial values: []
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.999,0.926,0.6,0.6]
          fit_limit_max: [1.1,1.02,1.5,1.2]
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_58_90"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_RV0_58_90"
              # initial values: []
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.999,0.926,0.6,0.6]
          fit_limit_max: [1.1,1.02,1.5,1.2]
        # - name: "pi0eta-to-gammagamma-pcmpcm_0-10"
        #   mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_0-10"
        #       # initial values: []
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_limit_min: [0.999,0.926,0.6,0.6]
        #   fit_limit_max: [1.1,1.02,1.5,1.2]
        # - name: "pi0eta-to-gammagamma-pcmpcm_10-20"
        #   mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_10-20"
        #       # initial values: []
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_limit_min: [0.999,0.926,0.6,0.6]
        #   fit_limit_max: [1.1,1.02,1.5,1.2]
        # - name: "pi0eta-to-gammagamma-pcmpcm_20-30"
        #   mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_20-30"
        #       # initial values: []
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_limit_min: [0.999,0.926,0.6,0.6]
        #   fit_limit_max: [1.1,1.02,1.5,1.2]
        # - name: "pi0eta-to-gammagamma-pcmpcm_30-40"
        #   mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_30-40"
        #       # initial values: []
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_limit_min: [0.999,0.926,0.6,0.6]
        #   fit_limit_max: [1.1,1.02,1.5,1.2]
        # - name: "pi0eta-to-gammagamma-pcmpcm_40-50"
        #   mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_40-50"
        #       # initial values: []
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_limit_min: [0.999,0.926,0.6,0.6]
        #   fit_limit_max: [1.1,1.02,1.5,1.2]
        # - name: "pi0eta-to-gammagamma-pcmpcm_50-60"
        #   mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_50-60"
        #       # initial values: []
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_limit_min: [0.999,0.926,0.6,0.6]
        #   fit_limit_max: [1.1,1.02,1.5,1.2]
        # - name: "pi0eta-to-gammagamma-pcmpcm_60-70"
        #   mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_60-70"
        #       # initial values: []
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_limit_min: [0.999,0.926,0.6,0.6]
        #   fit_limit_max: [1.1,1.02,1.5,1.2]
        # - name: "pi0eta-to-gammagamma-pcmpcm_70-80"
        #   mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_70-80"
        #       # initial values: []
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_limit_min: [0.999,0.926,0.6,0.6]
        #   fit_limit_max: [1.1,1.02,1.5,1.2]
        # - name: "pi0eta-to-gammagamma-pcmpcm_80-90"
        #   mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_80-90"
        #       # initial values: []
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_limit_min: [0.999,0.926,0.6,0.6]
        #   fit_limit_max: [1.1,1.02,1.5,1.2]
        # - name: "pi0eta-to-gammagamma-pcmpcm_90-100"
        #   mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_90-100"
        #       # initial values: []
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_limit_min: [0.999,0.926,0.6,0.6]
        #   fit_limit_max: [1.1,1.02,1.5,1.2]
        - name: "pi0eta-to-gammagamma-pcmpcm"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
              # initial values: []
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.999,0.926,0.6,0.6]
          fit_limit_max: [1.1,1.02,1.5,1.2]


