common:
    system : "pO"
    energy : ").61 TeV" #center-of-mass energy in TeV
    meson : "pi0"
    period : "EM_LHC25ad"
    plotting_type : "thesis"
    background_fit : "Asymmetric Gaussian fit"
    do_ptspectrum: True
    pt_bin: [0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00, 1.10, 1.20, 1.30, 1.40, 1.50, 1.60, 1.80, 2.00, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.20, 4.40, 4.60, 4.80, 5.00, 6.00, 7.00, 8.00, 9.00, 12.00]
    # this one pt_bin: [0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00, 1.10, 1.20, 1.30, 1.40, 1.50, 1.60, 1.80, 2.00, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.20, 4.40, 4.60, 4.80, 5.00, 5.50, 6.00, 6.50, 7.00, 7.50, 8.00, 9.00, 10.00, 12.00, 16.00]
    #pt_bin: [1., 2.0, 3.0, 5.0, 7.0, 9.0, 10.0, 20.0]
    #pt_bin: [0.40, 0.60, 0.80, 1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.50, 5.00, 5.50, 6.00, 7.00, 8.00, 9.00, 10.0, 12.0, 15.0, 20.0] #what I use
    #pt_bin: [0.45, 0.55, 0.65, 0.75, 0.85, 0.95, 1.1, 1.3, 1.5, 1.7, 1.9, 2.0, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.50, 5.00, 5.50, 6.00, 7.00, 8.00, 9.00, 10.0, 12.0, 15.0, 20.0] #what I use to compare with corr yield from charged pions
    #pt_bin: [0.40, 0.60, 0.80, 1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.50, 5.00, 5.50, 6.00, 7.00, 8.00, 9.00, 10.0, 12.0, 14.0]
    #pt_bin: [0., 0.50, 1.00, 1.25, 1.5, 2.0, 2.50, 3.00, 4.00, 5.00, 7.00, 20.0]
    #pt_bin: [0.1, 0.5, 0.7, 1.0, 1.5, 2.0, 2.5, 3.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 15., 19.8] #was 5.0, 10.0, .. using this one
    #pt_bin: [0, 0.5, 1., 2.0, 3.0, 5.0, 7.0, 9.0, 10.0, 20.0]
    #centrality_bin: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    centrality_bin: [0, 100]
    RV0_bin: [4,30,58,90]
    start_pT_bin: 1
    fit_min: [0.06] # previously 0.04
    fit_max: [0.18] #previously 0.2
    integral_min: [0.18]
    integral_max: [0.25]
    yield_min: [0.035] #yield_min - mean
    yield_max: [0.02] # previously 0.01 mean + yield_max
data:
    fit_func: ["gausexpquadratic"] #gausexplinear gausexpquadratic gausexpcube
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems:
      #  - name: "PCMPCM"
      #    cuts:
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_4_30"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.2,0.6]
          fit_limit_max: [1.2,1.02,2,1.3]
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_30_58"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.2,0.6]
          fit_limit_max: [1.2,1.02,2,1.3]
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_58_90"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.2,0.6]
          fit_limit_max: [1.2,1.02,2,1.3]
        - name: "pi0eta-to-gammagamma-pcmpcm"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.2,0.6]
          fit_limit_max: [1.2,1.02,2,1.3]
        #- name: "pi0eta-to-gammagamma-pcmpcm"
        #  mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
        #  fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #  fit_limit_min: [0.95,0.926,0.35,0.45]
        #  fit_limit_max: [1.2,1.05,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_0-10"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.35,0.45]
      #    fit_limit_max: [1.2,1.05,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_10-20"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.35,0.45]
      #    fit_limit_max: [1.2,1.05,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_20-30"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.35,0.45]
      #    fit_limit_max: [1.2,1.05,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_30-40"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.35,0.45]
      #    fit_limit_max: [1.2,1.05,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_40-50"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.35,0.45]
      #    fit_limit_max: [1.2,1.05,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_50-60"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.35,0.45]
      #    fit_limit_max: [1.2,1.05,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_60-70"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.35,0.45]
      #    fit_limit_max: [1.2,1.05,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_70-80"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.35,0.45]
      #    fit_limit_max: [1.2,1.05,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_80-90"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.35,0.45]
      #    fit_limit_max: [1.2,1.05,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_90-100"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.35,0.45]
      #    fit_limit_max: [1.2,1.05,1.3,1.1]
        
mc:
    fit_func: ["gausexp"]
    subsystems:
        # - name: "PCMPCM"
        #   cutnames:
        - "pi0eta-to-gammagamma-pcmpcm"

