common:
    system : "OO"
    energy : "5.36 TeV" #center-of-mass energy in TeV
    meson : "pi0" 
    period : "LHC25h3b"
    plotting_type: "thesis"
    background_fit: "Asymmetric Gaussian fit"
    do_ptspectrum: True
    pt_bin: [0.30,0.40,0.5, 0.60,0.7, 0.80,0.9, 1.00,1.1, 1.2 , 1.4 , 1.5 ,1.6 , 1.7 , 1.8,  1.9,  2.,   2.1 , 2.2 , 2.3 , 2.4 , 2.6,  2.8 ,3.  , 3.2 , 3.4 , 3.6 , 3.8 , 4. ,  4.3 , 4.6 , 5. ,  5.5 , 6. ,  6.5 , 7. ,  8. ,9. ,  9.9 ,11.8 ,14.6] #pt_bins 
    #pt_bin: [0.30,0.40,0.5, 0.60,0.7, 0.80,0.9, 1.00,1.1, 1.20,1.3, 1.40,1.5, 1.60, 1.80, 2.0, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.2,4.4,4.6,4.8, 5.00, 5.5, 6.00, 6.5, 7.00,7.5, 8.00, 9.00, 10.0, 12.0,16.0] #middle bins
    #pt_bin: [0.00,0.10,0.20,0.30,0.40,0.5, 0.60,0.7, 0.80,0.9, 1.00,1.1, 1.20,1.3, 1.40,1.5, 1.60, 1.80, 2.0, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.2,4.4,4.6,4.8, 5.00, 5.2,5.4,5.6,5.8, 6.00,6.5, 7.00,7.5, 8.00,8.5, 9.00,9.5, 10.0,10.5,11,11.5, 12.0,13,14, 15.0,20.0] #very small bins
    centrality_bin: [0, 20, 40, 60, 80, 100]
    RV0_bin: [4,30,58,90]
    RV0_general: [4, 90]
    start_pT_bin: 1
    fit_min: [0.06] # previously 0.06
    fit_max: [0.18] #previosly 0.2
    integral_min: [0.18] #previously 0.18
    integral_max: [0.25] #previously 0.25
    yield_min: [0.035] #previously 0.035
    yield_max: [0.02] # previously 0.02, before that 0.01
    leg_entry: "M.C. rec. #gamma (LHC25f3)"
data:
    fit_func: ["gausexplinear"] 
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems: 
        # - name: "PCMPCM"
          # cuts:
        - name: "pi0eta-to-gammagamma-pcmpcm"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
             # initial values: []
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.97,0.926,0.85,0.8]
          fit_limit_max: [1.2,1.02,1.5,1.1]
mc:
    fit_func: ["gausexp"] 
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems: 
        # - name: "PCMPCM"
          # cuts:
          #  - name: "pi0eta-to-gammagamma-pcmpcm_0-20"
          #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_0-20"
          #        # initial values: []
          #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          #    fit_limit_min: [0.999,0.926,0.6,0.6]
          #    fit_limit_max: [1.1,1.02,1.5,1.2]
          #  - name: "pi0eta-to-gammagamma-pcmpcm_20-40"
          #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_20-40"
          #        # initial values: []
          #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          #    fit_limit_min: [0.999,0.926,0.6,0.6]
          #    fit_limit_max: [1.1,1.02,1.5,1.2]
          #  - name: "pi0eta-to-gammagamma-pcmpcm_40-60"
          #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_40-60"
          #        # initial values: []
          #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          #    fit_limit_min: [0.999,0.926,0.6,0.6]
          #    fit_limit_max: [1.1,1.02,1.5,1.2]       
          #  - name: "pi0eta-to-gammagamma-pcmpcm_60-80"
          #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_60-80"
          #        # initial values: []
          #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          #    fit_limit_min: [0.999,0.926,0.6,0.6]
          #    fit_limit_max: [1.1,1.02,1.5,1.2]
          #  - name: "pi0eta-to-gammagamma-pcmpcm_80-100"
          #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_80-100"
          #        # initial values: []
          #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          #    fit_limit_min: [0.999,0.926,0.6,0.6]
          #    fit_limit_max: [1.1,1.02,1.5,1.2]
            - name: "pi0eta-to-gammagamma-pcmpcm_RV0_4_30"
              mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_RV0_4_30"
              fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
              fit_limit_min: [0.9,0.926,0.4,0.2]
              fit_limit_max: [1.1,1.02,1.5,1.2]
            - name: "pi0eta-to-gammagamma-pcmpcm_RV0_30_58"
              mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_RV0_30_58"
              fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
              fit_limit_min: [0.9,0.926,0.4,0.2]
              fit_limit_max: [1.1,1.02,1.5,1.2]
            - name: "pi0eta-to-gammagamma-pcmpcm_RV0_58_90"
              mc_name: "pi0eta-to-gammagamma-mc-pcmpcm_RV0_58_90"
              fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
              fit_limit_min: [0.9,0.926,0.4,0.2]
              fit_limit_max: [1.1,1.02,1.5,1.2]
            - name: "pi0eta-to-gammagamma-pcmpcm"
              mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
              fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
              fit_limit_min: [0.9,0.926,0.4,0.2]
              fit_limit_max: [1.1,1.02,1.5,1.2]