common:
    system : "Pb-Pb"
    energy : "5.36 TeV" #center-of-mass energy in TeV
    meson : "eta"
    period : "EM_LHC23"
    plotting_type: "thesis"
    background_fit: "Asymmetric Gaussian fit"
    do_ptspectrum: True
    #pt_bin: [1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 2.50, 3.00,  3.50, 4.00, 4.50, 5.00, 5.5, 6.00,  7.00, 8.00, 9.00, 15.0]
    # pt_bin: [0., 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 5.0, 7.0, 9.0, 10.0, 20.0] #was 5.0, 10.0
    pt_bin: [1., 2.0, 3.0, 5.0, 7.0, 9.0, 10.0, 20.0] #was 5.0, 10.0
    #centrality_bin: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    centrality_bin: [0, 20, 40, 60, 80, 100]
    start_pT_bin: 1
    RV0_bin: [4,30,58,90]
    fit_min: [0.4]
    fit_max: [0.7]
    integral_min: [0.65]
    integral_max: [0.7]
    yield_min: [0.065]
    yield_max: [0.04]

data:
    fit_func: ["gausexplinear"]
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems:
      #  - name: "PCMPCM"
      #    cuts:
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_4_30"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          initial_fit_parameters: [1.0, 0.548, 0.012, 0.016]
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.5,0.65]
          fit_limit_max: [1.2,1.02,1.3,1.1]
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_30_58"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.5,0.55]
          fit_limit_max: [1.2,1.02,1.3,1.4]
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_58_90"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.5,0.65]
          fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_0-10"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_10-20"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_20-30"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_30-40"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_40-50"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_50-60"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_60-70"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_70-80"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_80-90"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_90-100"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
        - name: "pi0eta-to-gammagamma-pcmpcm"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.5,0.5]
          fit_limit_max: [1.2,1.02,1.3,1.4]

mc:
    fit_func: ["gausexp"]
    subsystems:
        # - name: "PCMPCM"
        #   cutnames:
        - "pi0eta-to-gammagamma-pcmpcm"

