common:
    system : "Pb-Pb"
    energy : "5.36 TeV" #center-of-mass energy in TeV
    meson : "pi0"
    period : "EM_LHC23"
    plotting_type : "thesis"
    background_fit : "Asymmetric Gaussian fit"
    pt_bin: [0.40, 0.80, 1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.50, 5.00, 5.50, 6.00, 7.00, 8.00, 9.00, 10.0, 12.0, 15.0, 20.0] #what I use
    #pt_bin: [1., 2.0, 3.0, 5.0, 7.0, 9.0, 10.0, 20.0]
    #pt_bin: [0.40, 0.60, 0.80, 1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.50, 5.00, 5.50, 6.00, 7.00, 8.00, 9.00, 10.0, 12.0, 15.0, 20.0] #what I use
    #pt_bin: [0.45, 0.55, 0.65, 0.75, 0.85, 0.95, 1.1, 1.3, 1.5, 1.7, 1.9, 2.0, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.50, 5.00, 5.50, 6.00, 7.00, 8.00, 9.00, 10.0, 12.0, 15.0, 20.0] #what I use to compare with corr yield from charged pions
    #pt_bin: [0.40, 0.60, 0.80, 1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.50, 5.00, 5.50, 6.00, 7.00, 8.00, 9.00, 10.0, 12.0, 14.0]
    #pt_bin: [0., 0.50, 1.00, 1.25, 1.5, 2.0, 2.50, 3.00, 4.00, 5.00, 7.00, 20.0]
    #pt_bin: [0.1, 0.5, 0.7, 1.0, 1.5, 2.0, 2.5, 3.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 15., 19.8] #was 5.0, 10.0, .. using this one
    #pt_bin: [0, 0.5, 1., 2.0, 3.0, 5.0, 7.0, 9.0, 10.0, 20.0]
    RV0_bin: [4,30,58,90]
    occupancy_bin: ["0", "more"] #0, 10k, 30k, more
    start_pT_bin: 1
data:
    subsystems:
      diff_RV0:
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_4_30"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.012]
          fit_parameters_name: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.35,0.45]
          fit_param_limit_max: [1.2,1.05,1.3,1.1]
          fit_func: ["gausexpquadratic"]
          fit_range: [[0.06, 0.18]]
          scale_mix_range: [[0.18, 0.25]]
          yield_range: [[0.035, 0.02]]
          #fit_func: ["gausexpquadratic", "gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic", "gausexplinear", "gausexpquadratic", "gausexpquadratic", "gausexpquadratic"] #gausexplinear gausexpquadratic gausexpcube
          #fit_range: [[0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18]]
          #scale_mix_range: [[0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25]]
          #yield_range: [[0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02],[0.035, 0.02], [0.18, 0.25], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02]] #yield_min - mean and #yield_max + mean
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_30_58"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
          fit_parameters_name: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.35,0.45]
          fit_param_limit_max: [1.2,1.05,1.3,1.1]
          fit_func: ["gausexpquadratic", "gausexpquadratic","gausexpquadratic","gausexplinear","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic", "gausexpquadratic", "gausexpquadratic", "gausexpquadratic", "gausexpquadratic"] #gausexplinear gausexpquadratic gausexpcube
          fit_range: [[0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18]]
          scale_mix_range: [[0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25]]
          yield_range: [[0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02],[0.035, 0.02], [0.18, 0.25], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02]] #yield_min - mean and #yield_max + mean
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_58_90"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
          fit_parameters_name: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.35,0.30]
          fit_param_limit_max: [1.2,1.05,1.3,1.1]
          fit_func: ["gausexpquadratic", "gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexplinear","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic", "gausexpquadratic", "gausexpquadratic", "gausexpquadratic", "gausexpquadratic"] #gausexplinear gausexpquadratic gausexpcube
          fit_range: [[0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18]]
          scale_mix_range: [[0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25]]
          yield_range: [[0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02],[0.035, 0.02], [0.18, 0.25], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02]] #yield_min - mean and #yield_max + mean
        - name: "pi0eta-to-gammagamma-pcmpcm"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
          fit_parameters_name: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.35,0.45]
          fit_param_limit_max: [1.2,1.05,1.3,1.1]
          fit_func: ["gausexpquadratic"]
          fit_range: [[0.06, 0.18]]
          scale_mix_range: [[0.18, 0.25]]
          yield_range: [[0.035, 0.02]]
      diff_cent:
        - name: "pi0eta-to-gammagamma-pcmpcm_0-20"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
          fit_parameters_name: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.35,0.45]
          fit_param_limit_max: [1.2,1.05,1.3,1.1]
          fit_func: ["gausexplinear"]
          fit_range: [[0.06, 0.18]]
          scale_mix_range: [[0.18, 0.25]]
          yield_range: [[0.035, 0.02]]
        - name: "pi0eta-to-gammagamma-pcmpcm_20-40"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.35,0.45]
          fit_param_limit_max: [1.2,1.05,1.3,1.1]
          fit_func: ["gausexpquadratic"]
          fit_range: [[0.06, 0.18]]
          scale_mix_range: [[0.18, 0.25]]
          yield_range: [[0.035, 0.02]]
        - name: "pi0eta-to-gammagamma-pcmpcm_40-60"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.35,0.45]
          fit_param_limit_max: [1.2,1.05,1.3,1.1]
          fit_func: ["gausexpquadratic"]
          fit_range: [[0.06, 0.18]]
          scale_mix_range: [[0.18, 0.25]]
          yield_range: [[0.035, 0.02]]
        - name: "pi0eta-to-gammagamma-pcmpcm_60-80"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.35,0.45]
          fit_param_limit_max: [1.2,1.05,1.3,1.1]
          fit_func: ["gausexpquadratic"]
          fit_range: [[0.06, 0.18]]
          scale_mix_range: [[0.18, 0.25]]
          yield_range: [[0.035, 0.02]]
        - name: "pi0eta-to-gammagamma-pcmpcm_80-100"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.35,0.45]
          fit_param_limit_max: [1.2,1.05,1.3,1.1]
          fit_func: ["gausexpquadratic"]
          fit_range: [[0.06, 0.18]]
          scale_mix_range: [[0.18, 0.25]]
          yield_range: [[0.035, 0.02]]
        # - name: "pi0eta-to-gammagamma-pcmpcm_50-60"
        #   initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_param_limit_min: [0.95,0.926,0.35,0.45]
        #   fit_param_limit_max: [1.2,1.05,1.3,1.1]
        #   fit_func: ["gausexpquadratic"]
        #   fit_range: [[0.06, 0.18]]
        #   scale_mix_range: [[0.18, 0.25]]
        #   yield_range: [[0.035, 0.02]]
        # - name: "pi0eta-to-gammagamma-pcmpcm_60-70"
        #   initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_param_limit_min: [0.95,0.926,0.35,0.45]
        #   fit_param_limit_max: [1.2,1.05,1.3,1.1]
        #   fit_func: ["gausexpquadratic"]
        #   fit_range: [[0.06, 0.18]]
        #   scale_mix_range: [[0.18, 0.25]]
        #   yield_range: [[0.035, 0.02]]
        # - name: "pi0eta-to-gammagamma-pcmpcm_70-80"
        #   initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_param_limit_min: [0.95,0.926,0.35,0.45]
        #   fit_param_limit_max: [1.2,1.05,1.3,1.1]
        #   fit_func: ["gausexpquadratic"]
        #   fit_range: [[0.06, 0.18]]
        #   scale_mix_range: [[0.18, 0.25]]
        #   yield_range: [[0.035, 0.02]]
        # - name: "pi0eta-to-gammagamma-pcmpcm_80-90"
        #   initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_param_limit_min: [0.95,0.926,0.35,0.45]
        #   fit_param_limit_max: [1.2,1.05,1.3,1.1]
        #   fit_func: ["gausexpquadratic"]
        #   fit_range: [[0.06, 0.18]]
        #   scale_mix_range: [[0.18, 0.25]]
        #   yield_range: [[0.035, 0.02]]
        # - name: "pi0eta-to-gammagamma-pcmpcm_90-100"
        #   initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
        #   fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
        #   fit_param_limit_min: [0.95,0.926,0.35,0.45]
        #   fit_param_limit_max: [1.2,1.05,1.3,1.1]
        #   fit_func: ["gausexpquadratic"]
        #   fit_range: [[0.06, 0.18]]
        #   scale_mix_range: [[0.18, 0.25]]
        #   yield_range: [[0.035, 0.02]]
        - name: "pi0eta-to-gammagamma-pcmpcm"
          initial_fit_parameters: [1.0, 0.135, 0.006, 0.016]
          fit_parameters_name: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_param_limit_min: [0.95,0.926,0.35,0.45]
          fit_param_limit_max: [1.2,1.05,1.3,1.1]
          #if all of the pT ranges have, for instance, the same fit_range, then it's enough to just write one fit_range, a.k.a fit_range: [[0.06, 0.18]]
          fit_func: ["gausexpquadratic"]
          fit_range: [[0.06, 0.18]]
          scale_mix_range: [[0.18, 0.25]]
          yield_range: [[0.035, 0.02]]
          #fit_func: ["gausexpquadratic", "gausexpquadratic","gausexplinear","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic","gausexpquadratic", "gausexpquadratic", "gausexpquadratic", "gausexpquadratic", "gausexpquadratic"] #gausexplinear gausexpquadratic gausexpcube
          #fit_range: [[0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18], [0.06, 0.18]]
          #scale_mix_range: [[0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25], [0.18, 0.25]]
          #yield_range: [[0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02],[0.035, 0.02], [0.18, 0.25], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02], [0.035, 0.02]] #yield_min - mean and #yield_max + mean

