common:
    system : "OO"
    energy : "5.36 TeV" #center-of-mass energy in TeV
    meson : "pi0" 
    period : "LHC25ae"
    plotting_type : "thesis"
    background_fit : "Asymmetric Gaussian fit"
    do_ptspectrum: True
    pt_bin: [0.30,0.40,0.5, 0.60,0.7, 0.80,0.9, 1.00,1.1, 1.2 , 1.4 , 1.5 ,1.6 , 1.7 , 1.8,  1.9,  2.,   2.1 , 2.2 , 2.3 , 2.4 , 2.6,  2.8 ,3.  , 3.2 , 3.4 , 3.6 , 3.8 , 4. ,  4.3 , 4.6 , 5. ,  5.5 , 6. ,  6.5 , 7. ,  8. ,9. ,  9.9 ,11.8 ,14.6] #pt_bins 
    #pt_bin: [0.30,0.40,0.5, 0.60,0.7, 0.80,0.9, 1.00,1.1, 1.20,1.3, 1.40,1.5, 1.60, 1.80, 2.0, 2.20, 2.40, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80, 4.00, 4.2,4.4,4.6,4.8, 5.00, 5.5, 6.00, 6.5, 7.00,7.5, 8.00, 9.00, 10.0, 12.0,16.0] #middle bins
    #centrality_bin: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    centrality_bin: [0, 20, 40, 60, 80, 100]
    RV0_bin: [4,30,58,90]
    RV0_general: [4, 90]
    start_pT_bin: 1
    fit_min: [0.06] # previously 0.04
    fit_max: [0.18] #previously 0.2 
    integral_min: [0.18] #previously 0.18
    integral_max: [0.25] #previously 0.25
    yield_min: [0.065] #previously 0.035
    #yield_min: [0.01] #smallRange
    #yield_min: [0.075] #bigRange
    yield_max: [0.04] # previously 0.02, before that 0.01
    #yield_max: [0.005] #smallRange
    #yield_max: [0.045] #bigRange
data:
    fit_func: ["gausexplinear"] #gausexplinear gausexpquadratic
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems: 
      #  - name: "PCMPCM"
      #    cuts:
      #  - name: "pi0eta-to-gammagamma-pcmpcm"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1]
      #  - name: "pi0eta-to-gammagamma-pcmpcm_0-20"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1] 
      #  - name: "pi0eta-to-gammagamma-pcmpcm_20-40"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1] 
      #  - name: "pi0eta-to-gammagamma-pcmpcm_40-60"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1] 
      #  - name: "pi0eta-to-gammagamma-pcmpcm_60-80"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1] 
      #  - name: "pi0eta-to-gammagamma-pcmpcm_80-100"
      #    mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
      #    fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
      #    fit_limit_min: [0.95,0.926,0.5,0.65]
      #    fit_limit_max: [1.2,1.02,1.3,1.1] 
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_4_30"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.25,0.25]
          fit_limit_max: [1.2,1.02,1.5,1.1]
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_30_58"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.25,0.25]
          fit_limit_max: [1.2,1.02,1.5,1.1]
        - name: "pi0eta-to-gammagamma-pcmpcm_RV0_58_90"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.25,0.25]
          fit_limit_max: [1.2,1.02,1.5,1.1]
        - name: "pi0eta-to-gammagamma-pcmpcm"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.25,0.25]
          fit_limit_max: [1.2,1.02,1.5,1.1]
mc:
    fit_func: ["gausexp"] 
    subsystems: 
        # - name: "PCMPCM"
        #   cutnames:
        - "pi0eta-to-gammagamma-pcmpcm"
        